export const ACTION_SET_USERNAME = 'ACTION_SET_USERNAME';
export const ACTION_SET_EMAIL = 'ACTION_SET_EMAIL';

export const ACTION_SET_USERFIRSTNAME = 'ACTION_SET_USERFIRSTNAME';
export const ACTION_SET_LASTNAME = 'ACTION_SET_LASTNAME';

export const ACTION_SET_STREETADDRESS = 'ACTION_SET_STREETADDRESS';
export const ACTION_SET_UNITNUMBER = 'ACTION_SET_UNITNUMBER';
export const ACTION_SET_CITY = 'ACTION_SET_CITY';
export const ACTION_SET_STATE = 'ACTION_SET_STATE';
export const ACTION_SET_ZIP = 'ACTION_SET_ZIP';